<?php

declare(strict_types=1);

namespace Siganushka\ApiProblem;

/**
 * Problem Details for HTTP APIs.
 *
 * This document defines a "problem detail" as a way to carry machine-
 * readable details of errors in a HTTP response to avoid the need to
 * define new error response formats for HTTP APIs.
 *
 * @see https://tools.ietf.org/html/rfc7807
 */
interface ApiProblemInterface
{
    /**
     * A URI reference [RFC3986] that identifies the
     * problem type. This specification encourages that, when
     * dereferenced, it provide human-readable documentation for the
     * problem type (e.g., using HTML [W3C.REC-html5-20141028]). When
     * this member is not present, its value is assumed to be
     * "about:blank".
     */
    public function getType(): string;

    /**
     * A short, human-readable summary of the problem
     * type. It SHOULD NOT change from occurrence to occurrence of the
     * problem, except for purposes of localization (e.g., using
     * proactive content negotiation; see [RFC7231], Section 3.4).
     */
    public function getTitle(): string;

    /**
     * The HTTP status code ([RFC7231], Section 6)
     * generated by the origin server for this occurrence of the problem.
     */
    public function getStatus(): int;

    /**
     * A human-readable explanation specific to this
     * occurrence of the problem.
     */
    public function getDetail(): string;
}
